### ISSUE TITLE
Secreto hardcodeado en código (authToken)

### ISSUE THREAD

**Issue by cybercamphackathon** [hedesil/atlas-frontend#1]
Se ha encontrado un secreto hardcodeado en el código, lo cual no es una buena práctica, incluso si es para pruebas o desarrollo local. En éste caso además de borrar el token del código, al ser un token JWT, será necesario rotar la clave de firmado del servidor en el caso de no haber caducado el token. Otra opción es tener la capacidad de blacklistear tokens.

Al inspeccionar el scope y validez del token, se ve que el token ha caducado ya pero sigue siendo un token con bastante acceso:
```
{
    "id": 1,
    "functionalities": [
        "DELETE DEPARTMENTS",
        "MODIFY DEPARTMENTS",
        "ADD DEPARTMENTS",
        "GET DEPARTMENTS",
        "DELETE AREAS",
        "MODIFY AREAS",
        "ADD AREAS",
        "GET AREAS",
        "DELETE USERS",
        "MODIFY USERS",
        "ADD USERS",
        "GET USERS",
        "DELETE GROUPS",
        "MODIFY GROUPS",
        "ADD GROUPS",
        "GET GROUPS",
        "DELETE PROFILES",
        "MODIFY PROFILES",
        "ADD PROFILES",
        "GET PROFILES",
        "DELETE COMPANIES",
        "MODIFY COMPANIES",
        "ADD COMPANIES",
        "GET COMPANIES"
    ],
    "groups": [],
    "companies": [
        1
    ],
    "iat": 1573934126,
    "exp": 1573937726
}
```

https://github.com/hedesil/atlas-frontend/blob/master/src/app/search/search.service.ts#L12

**Comment by hedesil** [comment]
Se ha eliminado el componente de pruebas que contenía esa clave hardcodeada.
